version: '3.8'

services:
  postgres_db:
    image: postgres:15
    restart: always
    hostname: db_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init_db.sql
  telegram_bot:
    build: .
    user: ${CURRENT_UID}
    env_file:
      - .env
    hostname: telegram_bot
    depends_on:
      - postgres_db
    restart: on-failure

volumes:
  postgres_data:
